"""
Create Shareable Package
Packages the viewer with all images into a shareable ZIP file.
"""

import shutil
from datetime import datetime
from pathlib import Path


def create_shareable_package():
    """Create a complete shareable package with viewer and images."""

    print("\n" + "=" * 70)
    print("  CREATING SHAREABLE PACKAGE")
    print("=" * 70 + "\n")

    # Create package directory
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    package_name = f"face_verification_report_{timestamp}"
    package_dir = Path(package_name)

    if package_dir.exists():
        shutil.rmtree(package_dir)

    package_dir.mkdir()

    print(f"[*] Creating package: {package_name}")

    # Copy viewer and fix image paths
    print("[*] Copying viewer and fixing image paths...")
    viewer_path = Path("output/viewer.html")
    with open(viewer_path, 'r', encoding='utf-8') as f:
        viewer_content = f.read()

    # Fix image paths: change '../images/' to 'images/'
    viewer_content = viewer_content.replace("'../' + comp.person1.image_path", "comp.person1.image_path")
    viewer_content = viewer_content.replace("'../' + comp.person2.image_path", "comp.person2.image_path")

    with open(package_dir / "viewer.html", 'w', encoding='utf-8') as f:
        f.write(viewer_content)

    # Copy images folder
    print("[*] Copying images...")
    if Path("images").exists():
        shutil.copytree("images", package_dir / "images")

    # Copy other reports (optional)
    print("[*] Copying additional reports...")
    reports_to_copy = [
        "output/verification_report.html",
        "output/verification_grid_all.png",
        "output/verification_heatmap.png"
    ]

    reports_dir = package_dir / "additional_reports"
    reports_dir.mkdir()

    for report in reports_to_copy:
        if Path(report).exists():
            shutil.copy(report, reports_dir / Path(report).name)

    # Copy person galleries
    for gallery in Path("output").glob("gallery_person_*.png"):
        shutil.copy(gallery, reports_dir / gallery.name)

    # Create README
    print("[*] Creating README...")
    readme_content = f"""
# Face Verification Report Package

Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## How to View

1. **OPEN: viewer.html**
   - Double-click to open in your browser
   - Browse through all face comparisons
   - Use navigation buttons or keyboard shortcuts

2. **Features:**
   - Interactive carousel viewer
   - Side-by-side image comparison
   - Full statistics and details
   - Keyboard shortcuts (Arrow keys, Home/End)

## Folder Structure

```
{package_name}/
├── viewer.html              # Main interactive viewer (START HERE)
├── images/                  # All person images
│   ├── person_0001/
│   ├── person_0002/
│   └── person_0003/
└── additional_reports/      # Additional visualizations
    ├── verification_report.html
    ├── verification_grid_all.png
    ├── verification_heatmap.png
    └── gallery_person_*.png
```

## System Requirements

- Any modern web browser (Chrome, Firefox, Edge, Safari)
- No installation required
- Works offline
- No internet connection needed

## Privacy Note

This package contains all images used in the analysis.
Only share with authorized recipients.

## Support

For questions about the face verification system:
- Check the main viewer (viewer.html)
- Review additional reports in additional_reports/

---
Generated by DeepFace Practice Project
"""

    with open(package_dir / "README.txt", 'w', encoding='utf-8') as f:
        f.write(readme_content)

    # Create ZIP file
    print("[*] Creating ZIP archive...")
    zip_name = f"{package_name}.zip"
    shutil.make_archive(package_name, 'zip', '.', package_name)

    # Get size
    zip_size = Path(zip_name).stat().st_size / (1024 * 1024)  # MB

    print("\n" + "=" * 70)
    print("  PACKAGE CREATED SUCCESSFULLY!")
    print("=" * 70)

    print(f"\n  File: {zip_name}")
    print(f"  Size: {zip_size:.1f} MB")

    print("\n" + "=" * 70)
    print("  HOW TO SHARE")
    print("=" * 70)

    print("""
1. EMAIL (if size < 25MB):
   - Attach {zip_name} to email
   - Recipient: Extract ZIP and open viewer.html

2. CLOUD STORAGE:
   - Upload to Google Drive / Dropbox / OneDrive
   - Share link with recipients
   - Recipient: Download, extract, open viewer.html

3. USB DRIVE:
   - Copy {zip_name} to USB
   - Or copy extracted folder directly
   - Recipient: Open viewer.html from USB

4. INTERNAL NETWORK:
   - Place on shared network drive
   - Team can access directly

5. WEB HOSTING (Advanced):
   - Upload to web server
   - Access via URL (http://yourserver.com/viewer.html)
""".format(zip_name=zip_name))

    print("=" * 70)
    print("\n[OK] Package ready to share!")
    print(f"     {zip_name}\n")

    # Cleanup temp directory
    shutil.rmtree(package_dir)


if __name__ == "__main__":
    try:
        create_shareable_package()
    except Exception as e:
        print(f"\n[X] Error: {e}")
        import traceback

        traceback.print_exc()
